# Generated by Django 3.1.2 on 2021-02-03 04:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_medi', models.CharField(max_length=200, unique=True)),
                ('slug_medi', models.SlugField(max_length=200, unique=True)),
                ('updated_on_medi', models.DateTimeField(default=django.utils.timezone.now)),
                ('content_medi', models.TextField()),
                ('created_on_medi', models.DateTimeField(default=django.utils.timezone.now)),
                ('status_medi', models.IntegerField(choices=[(0, 'Drafst'), (1, 'Publish')], default=0)),
                ('image_medi', models.ImageField(default='default.jpg', upload_to='medical/media/image-pics')),
                ('author_medi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_blog_posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
